-- 用户表（新增 banned 字段）
CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  nickname TEXT NOT NULL,
  points INTEGER DEFAULT 0,
  is_admin INTEGER DEFAULT 0,
  banned INTEGER DEFAULT 0,
  last_checkin TEXT
);

-- 连飞活动
CREATE TABLE IF NOT EXISTS events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  description TEXT,
  creator_id INTEGER,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 活动报名
CREATE TABLE IF NOT EXISTS signups (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  event_id INTEGER,
  user_id INTEGER,
  callsign TEXT,
  aircraft TEXT,
  parking TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 聊天
CREATE TABLE IF NOT EXISTS chat (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nickname TEXT,
  message TEXT,
  time DATETIME DEFAULT CURRENT_TIMESTAMP
);
