CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE,
  nickname TEXT,
  password TEXT,
  points INTEGER DEFAULT 0,
  is_admin INTEGER DEFAULT 0,
  status INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT,
  description TEXT,
  creator_id INTEGER,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS event_signups (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  event_id INTEGER,
  user_id INTEGER,
  callsign TEXT,
  aircraft TEXT,
  parking TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
