name = "mtyafa-platform"
compatibility_date = "2026-08-25"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "mtyafa-db"
database_id = "YOUR_D1_DATABASE_ID"

functions_dir = "functions"
